# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/oracle_test/abc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/oracle_test/abc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/oracle_test/abc/CMakeFiles /root/oracle_test/abc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/oracle_test/abc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BusServer

# Build rule for target.
BusServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BusServer
.PHONY : BusServer

# fast build rule for target.
BusServer/fast:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/build
.PHONY : BusServer/fast

src/crc_itu.o: src/crc_itu.c.o
.PHONY : src/crc_itu.o

# target to build an object file
src/crc_itu.c.o:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/crc_itu.c.o
.PHONY : src/crc_itu.c.o

src/crc_itu.i: src/crc_itu.c.i
.PHONY : src/crc_itu.i

# target to preprocess a source file
src/crc_itu.c.i:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/crc_itu.c.i
.PHONY : src/crc_itu.c.i

src/crc_itu.s: src/crc_itu.c.s
.PHONY : src/crc_itu.s

# target to generate assembly for a file
src/crc_itu.c.s:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/crc_itu.c.s
.PHONY : src/crc_itu.c.s

src/dispatcher.o: src/dispatcher.c.o
.PHONY : src/dispatcher.o

# target to build an object file
src/dispatcher.c.o:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/dispatcher.c.o
.PHONY : src/dispatcher.c.o

src/dispatcher.i: src/dispatcher.c.i
.PHONY : src/dispatcher.i

# target to preprocess a source file
src/dispatcher.c.i:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/dispatcher.c.i
.PHONY : src/dispatcher.c.i

src/dispatcher.s: src/dispatcher.c.s
.PHONY : src/dispatcher.s

# target to generate assembly for a file
src/dispatcher.c.s:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/dispatcher.c.s
.PHONY : src/dispatcher.c.s

src/engine.o: src/engine.c.o
.PHONY : src/engine.o

# target to build an object file
src/engine.c.o:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/engine.c.o
.PHONY : src/engine.c.o

src/engine.i: src/engine.c.i
.PHONY : src/engine.i

# target to preprocess a source file
src/engine.c.i:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/engine.c.i
.PHONY : src/engine.c.i

src/engine.s: src/engine.c.s
.PHONY : src/engine.s

# target to generate assembly for a file
src/engine.c.s:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/engine.c.s
.PHONY : src/engine.c.s

src/gps_user.o: src/gps_user.c.o
.PHONY : src/gps_user.o

# target to build an object file
src/gps_user.c.o:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/gps_user.c.o
.PHONY : src/gps_user.c.o

src/gps_user.i: src/gps_user.c.i
.PHONY : src/gps_user.i

# target to preprocess a source file
src/gps_user.c.i:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/gps_user.c.i
.PHONY : src/gps_user.c.i

src/gps_user.s: src/gps_user.c.s
.PHONY : src/gps_user.s

# target to generate assembly for a file
src/gps_user.c.s:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/gps_user.c.s
.PHONY : src/gps_user.c.s

src/listener.o: src/listener.c.o
.PHONY : src/listener.o

# target to build an object file
src/listener.c.o:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/listener.c.o
.PHONY : src/listener.c.o

src/listener.i: src/listener.c.i
.PHONY : src/listener.i

# target to preprocess a source file
src/listener.c.i:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/listener.c.i
.PHONY : src/listener.c.i

src/listener.s: src/listener.c.s
.PHONY : src/listener.s

# target to generate assembly for a file
src/listener.c.s:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/listener.c.s
.PHONY : src/listener.c.s

src/logger.o: src/logger.c.o
.PHONY : src/logger.o

# target to build an object file
src/logger.c.o:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/logger.c.o
.PHONY : src/logger.c.o

src/logger.i: src/logger.c.i
.PHONY : src/logger.i

# target to preprocess a source file
src/logger.c.i:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/logger.c.i
.PHONY : src/logger.c.i

src/logger.s: src/logger.c.s
.PHONY : src/logger.s

# target to generate assembly for a file
src/logger.c.s:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/logger.c.s
.PHONY : src/logger.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/main.c.s
.PHONY : src/main.c.s

src/msg.o: src/msg.c.o
.PHONY : src/msg.o

# target to build an object file
src/msg.c.o:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/msg.c.o
.PHONY : src/msg.c.o

src/msg.i: src/msg.c.i
.PHONY : src/msg.i

# target to preprocess a source file
src/msg.c.i:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/msg.c.i
.PHONY : src/msg.c.i

src/msg.s: src/msg.c.s
.PHONY : src/msg.s

# target to generate assembly for a file
src/msg.c.s:
	$(MAKE) -f CMakeFiles/BusServer.dir/build.make CMakeFiles/BusServer.dir/src/msg.c.s
.PHONY : src/msg.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... BusServer"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/crc_itu.o"
	@echo "... src/crc_itu.i"
	@echo "... src/crc_itu.s"
	@echo "... src/dispatcher.o"
	@echo "... src/dispatcher.i"
	@echo "... src/dispatcher.s"
	@echo "... src/engine.o"
	@echo "... src/engine.i"
	@echo "... src/engine.s"
	@echo "... src/gps_user.o"
	@echo "... src/gps_user.i"
	@echo "... src/gps_user.s"
	@echo "... src/listener.o"
	@echo "... src/listener.i"
	@echo "... src/listener.s"
	@echo "... src/logger.o"
	@echo "... src/logger.i"
	@echo "... src/logger.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/msg.o"
	@echo "... src/msg.i"
	@echo "... src/msg.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

